{% set version = "0.4.3" %}

package:
  name: robotframework-seriallibrary
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/robotframework-seriallibrary/robotframework-seriallibrary-{{ version }}.tar.gz
  sha256: f20befe5c1106dd8ddca9f60a2f18bf5ec7d5f06f6f09a03fa66bae54777e6bb
  patches:
    - 0000-fix-install-requires-install-requires.patch

build:
  number: 1
  noarch: python
  script:
    # remove the broken `pyproject.toml` for now
    - {{ PYTHON }} -c "__import__('os').unlink('pyproject.toml')"
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    # could be restored later, but `setup.py`` is also fine, while supported
    # - poetry-core >=1.0.0
    - setuptools
    - python {{ python_min }}
  run:
    - pyserial
    - python >={{ python_min }}
    - robotframework

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - SerialLibrary
  commands:
    - pip check

about:
  home: https://github.com/whosaysni/robotframework-seriallibrary
  summary: Robot Framework test library for serial connection
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdmarques
    - bollwyvl
